package bham.team.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AuthenticationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAuthenticationAllPropertiesEquals(Authentication expected, Authentication actual) {
        assertAuthenticationAutoGeneratedPropertiesEquals(expected, actual);
        assertAuthenticationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAuthenticationAllUpdatablePropertiesEquals(Authentication expected, Authentication actual) {
        assertAuthenticationUpdatableFieldsEquals(expected, actual);
        assertAuthenticationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAuthenticationAutoGeneratedPropertiesEquals(Authentication expected, Authentication actual) {
        assertThat(expected)
            .as("Verify Authentication auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAuthenticationUpdatableFieldsEquals(Authentication expected, Authentication actual) {
        assertThat(expected)
            .as("Verify Authentication relevant properties")
            .satisfies(e -> assertThat(e.getPassword()).as("check password").isEqualTo(actual.getPassword()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAuthenticationUpdatableRelationshipsEquals(Authentication expected, Authentication actual) {
        // empty method
    }
}
