package bham.team.domain;

import static bham.team.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ItemAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertItemAllPropertiesEquals(Item expected, Item actual) {
        assertItemAutoGeneratedPropertiesEquals(expected, actual);
        assertItemAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertItemAllUpdatablePropertiesEquals(Item expected, Item actual) {
        assertItemUpdatableFieldsEquals(expected, actual);
        assertItemUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertItemAutoGeneratedPropertiesEquals(Item expected, Item actual) {
        assertThat(expected)
            .as("Verify Item auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertItemUpdatableFieldsEquals(Item expected, Item actual) {
        assertThat(expected)
            .as("Verify Item relevant properties")
            .satisfies(e -> assertThat(e.getItemTitle()).as("check itemTitle").isEqualTo(actual.getItemTitle()))
            .satisfies(e ->
                assertThat(e.getItemPrice()).as("check itemPrice").usingComparator(bigDecimalCompareTo).isEqualTo(actual.getItemPrice())
            )
            .satisfies(e -> assertThat(e.getItemSize()).as("check itemSize").isEqualTo(actual.getItemSize()))
            .satisfies(e -> assertThat(e.getItemCondition()).as("check itemCondition").isEqualTo(actual.getItemCondition()))
            .satisfies(e -> assertThat(e.getItemCategory()).as("check itemCategory").isEqualTo(actual.getItemCategory()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()))
            .satisfies(e -> assertThat(e.getItemColour()).as("check itemColour").isEqualTo(actual.getItemColour()))
            .satisfies(e -> assertThat(e.getItemImage()).as("check itemImage").isEqualTo(actual.getItemImage()))
            .satisfies(e ->
                assertThat(e.getItemImageContentType()).as("check itemImage contenty type").isEqualTo(actual.getItemImageContentType())
            )
            .satisfies(e -> assertThat(e.getTimeListed()).as("check timeListed").isEqualTo(actual.getTimeListed()))
            .satisfies(e -> assertThat(e.getItemLike()).as("check itemLike").isEqualTo(actual.getItemLike()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertItemUpdatableRelationshipsEquals(Item expected, Item actual) {
        // empty method
    }
}
