package bham.team.domain;

import static bham.team.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class ProductStatusAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductStatusAllPropertiesEquals(ProductStatus expected, ProductStatus actual) {
        assertProductStatusAutoGeneratedPropertiesEquals(expected, actual);
        assertProductStatusAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductStatusAllUpdatablePropertiesEquals(ProductStatus expected, ProductStatus actual) {
        assertProductStatusUpdatableFieldsEquals(expected, actual);
        assertProductStatusUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductStatusAutoGeneratedPropertiesEquals(ProductStatus expected, ProductStatus actual) {
        assertThat(expected)
            .as("Verify ProductStatus auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductStatusUpdatableFieldsEquals(ProductStatus expected, ProductStatus actual) {
        assertThat(expected)
            .as("Verify ProductStatus relevant properties")
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()))
            .satisfies(e -> assertThat(e.getMeetingTime()).as("check meetingTime").isEqualTo(actual.getMeetingTime()))
            .satisfies(e -> assertThat(e.getMeetingLocation()).as("check meetingLocation").isEqualTo(actual.getMeetingLocation()))
            .satisfies(e -> assertThat(e.getChatLink()).as("check chatLink").isEqualTo(actual.getChatLink()))
            .satisfies(e ->
                assertThat(e.getCreatedAt())
                    .as("check createdAt")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(actual.getCreatedAt())
            )
            .satisfies(e ->
                assertThat(e.getUpdatedAt())
                    .as("check updatedAt")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(actual.getUpdatedAt())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductStatusUpdatableRelationshipsEquals(ProductStatus expected, ProductStatus actual) {
        // empty method
    }
}
