package bham.team.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProfileDetailsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfileDetailsAllPropertiesEquals(ProfileDetails expected, ProfileDetails actual) {
        assertProfileDetailsAutoGeneratedPropertiesEquals(expected, actual);
        assertProfileDetailsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfileDetailsAllUpdatablePropertiesEquals(ProfileDetails expected, ProfileDetails actual) {
        assertProfileDetailsUpdatableFieldsEquals(expected, actual);
        assertProfileDetailsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfileDetailsAutoGeneratedPropertiesEquals(ProfileDetails expected, ProfileDetails actual) {
        assertThat(expected)
            .as("Verify ProfileDetails auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfileDetailsUpdatableFieldsEquals(ProfileDetails expected, ProfileDetails actual) {
        assertThat(expected)
            .as("Verify ProfileDetails relevant properties")
            .satisfies(e -> assertThat(e.getBioImage()).as("check bioImage").isEqualTo(actual.getBioImage()))
            .satisfies(e ->
                assertThat(e.getBioImageContentType()).as("check bioImage contenty type").isEqualTo(actual.getBioImageContentType())
            )
            .satisfies(e -> assertThat(e.getUserName()).as("check userName").isEqualTo(actual.getUserName()))
            .satisfies(e -> assertThat(e.getBirthDate()).as("check birthDate").isEqualTo(actual.getBirthDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfileDetailsUpdatableRelationshipsEquals(ProfileDetails expected, ProfileDetails actual) {
        assertThat(expected)
            .as("Verify ProfileDetails relationships")
            .satisfies(e -> assertThat(e.getLocations()).as("check locations").isEqualTo(actual.getLocations()))
            .satisfies(e -> assertThat(e.getConversations()).as("check conversations").isEqualTo(actual.getConversations()));
    }
}
