package bham.team.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UserRecommendationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserRecommendationAllPropertiesEquals(UserRecommendation expected, UserRecommendation actual) {
        assertUserRecommendationAutoGeneratedPropertiesEquals(expected, actual);
        assertUserRecommendationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserRecommendationAllUpdatablePropertiesEquals(UserRecommendation expected, UserRecommendation actual) {
        assertUserRecommendationUpdatableFieldsEquals(expected, actual);
        assertUserRecommendationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserRecommendationAutoGeneratedPropertiesEquals(UserRecommendation expected, UserRecommendation actual) {
        assertThat(expected)
            .as("Verify UserRecommendation auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserRecommendationUpdatableFieldsEquals(UserRecommendation expected, UserRecommendation actual) {
        assertThat(expected)
            .as("Verify UserRecommendation relevant properties")
            .satisfies(e -> assertThat(e.getReason()).as("check reason").isEqualTo(actual.getReason()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserRecommendationUpdatableRelationshipsEquals(UserRecommendation expected, UserRecommendation actual) {
        // empty method
    }
}
