package bham.team.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UserDetailsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserDetailsAllPropertiesEquals(UserDetails expected, UserDetails actual) {
        assertUserDetailsAutoGeneratedPropertiesEquals(expected, actual);
        assertUserDetailsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserDetailsAllUpdatablePropertiesEquals(UserDetails expected, UserDetails actual) {
        assertUserDetailsUpdatableFieldsEquals(expected, actual);
        assertUserDetailsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserDetailsAutoGeneratedPropertiesEquals(UserDetails expected, UserDetails actual) {
        assertThat(expected)
            .as("Verify UserDetails auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserDetailsUpdatableFieldsEquals(UserDetails expected, UserDetails actual) {
        assertThat(expected)
            .as("Verify UserDetails relevant properties")
            .satisfies(e -> assertThat(e.getFirstName()).as("check firstName").isEqualTo(actual.getFirstName()))
            .satisfies(e -> assertThat(e.getLastName()).as("check lastName").isEqualTo(actual.getLastName()))
            .satisfies(e -> assertThat(e.getEmail()).as("check email").isEqualTo(actual.getEmail()))
            .satisfies(e -> assertThat(e.getProfilePic()).as("check profilePic").isEqualTo(actual.getProfilePic()))
            .satisfies(e ->
                assertThat(e.getProfilePicContentType()).as("check profilePic contenty type").isEqualTo(actual.getProfilePicContentType())
            )
            .satisfies(e -> assertThat(e.getLastActive()).as("check lastActive").isEqualTo(actual.getLastActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserDetailsUpdatableRelationshipsEquals(UserDetails expected, UserDetails actual) {
        assertThat(expected)
            .as("Verify UserDetails relationships")
            .satisfies(e -> assertThat(e.getConversations()).as("check conversations").isEqualTo(actual.getConversations()));
    }
}
