package bham.team.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UserDetailsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserDetailsAllPropertiesEquals(UserDetails expected, UserDetails actual) {
        assertUserDetailsAutoGeneratedPropertiesEquals(expected, actual);
        assertUserDetailsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserDetailsAllUpdatablePropertiesEquals(UserDetails expected, UserDetails actual) {
        assertUserDetailsUpdatableFieldsEquals(expected, actual);
        assertUserDetailsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserDetailsAutoGeneratedPropertiesEquals(UserDetails expected, UserDetails actual) {
        assertThat(expected)
            .as("Verify UserDetails auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserDetailsUpdatableFieldsEquals(UserDetails expected, UserDetails actual) {
        assertThat(expected)
            .as("Verify UserDetails relevant properties")
            .satisfies(e -> assertThat(e.getBioImage()).as("check bioImage").isEqualTo(actual.getBioImage()))
            .satisfies(e ->
                assertThat(e.getBioImageContentType()).as("check bioImage contenty type").isEqualTo(actual.getBioImageContentType())
            )
            .satisfies(e -> assertThat(e.getUserName()).as("check userName").isEqualTo(actual.getUserName()))
            .satisfies(e -> assertThat(e.getFirstName()).as("check firstName").isEqualTo(actual.getFirstName()))
            .satisfies(e -> assertThat(e.getLastName()).as("check lastName").isEqualTo(actual.getLastName()))
            .satisfies(e -> assertThat(e.getGender()).as("check gender").isEqualTo(actual.getGender()))
            .satisfies(e -> assertThat(e.getBirthDate()).as("check birthDate").isEqualTo(actual.getBirthDate()))
            .satisfies(e -> assertThat(e.getEmail()).as("check email").isEqualTo(actual.getEmail()))
            .satisfies(e -> assertThat(e.getPhoneNumber()).as("check phoneNumber").isEqualTo(actual.getPhoneNumber()))
            .satisfies(e -> assertThat(e.getPreferences()).as("check preferences").isEqualTo(actual.getPreferences()))
            .satisfies(e -> assertThat(e.getRating()).as("check rating").isEqualTo(actual.getRating()))
            .satisfies(e -> assertThat(e.getAddress()).as("check address").isEqualTo(actual.getAddress()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserDetailsUpdatableRelationshipsEquals(UserDetails expected, UserDetails actual) {
        // empty method
    }
}
