package bham.team.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UserInteractionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserInteractionAllPropertiesEquals(UserInteraction expected, UserInteraction actual) {
        assertUserInteractionAutoGeneratedPropertiesEquals(expected, actual);
        assertUserInteractionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserInteractionAllUpdatablePropertiesEquals(UserInteraction expected, UserInteraction actual) {
        assertUserInteractionUpdatableFieldsEquals(expected, actual);
        assertUserInteractionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserInteractionAutoGeneratedPropertiesEquals(UserInteraction expected, UserInteraction actual) {
        assertThat(expected)
            .as("Verify UserInteraction auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserInteractionUpdatableFieldsEquals(UserInteraction expected, UserInteraction actual) {
        assertThat(expected)
            .as("Verify UserInteraction relevant properties")
            .satisfies(e -> assertThat(e.getType()).as("check type").isEqualTo(actual.getType()))
            .satisfies(e -> assertThat(e.getDetails()).as("check details").isEqualTo(actual.getDetails()))
            .satisfies(e -> assertThat(e.getInteractionDate()).as("check interactionDate").isEqualTo(actual.getInteractionDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserInteractionUpdatableRelationshipsEquals(UserInteraction expected, UserInteraction actual) {
        // empty method
    }
}
