package bham.team.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UserSearchHistoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserSearchHistoryAllPropertiesEquals(UserSearchHistory expected, UserSearchHistory actual) {
        assertUserSearchHistoryAutoGeneratedPropertiesEquals(expected, actual);
        assertUserSearchHistoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserSearchHistoryAllUpdatablePropertiesEquals(UserSearchHistory expected, UserSearchHistory actual) {
        assertUserSearchHistoryUpdatableFieldsEquals(expected, actual);
        assertUserSearchHistoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserSearchHistoryAutoGeneratedPropertiesEquals(UserSearchHistory expected, UserSearchHistory actual) {
        assertThat(expected)
            .as("Verify UserSearchHistory auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserSearchHistoryUpdatableFieldsEquals(UserSearchHistory expected, UserSearchHistory actual) {
        assertThat(expected)
            .as("Verify UserSearchHistory relevant properties")
            .satisfies(e -> assertThat(e.getSearchQuery()).as("check searchQuery").isEqualTo(actual.getSearchQuery()))
            .satisfies(e -> assertThat(e.getFilters()).as("check filters").isEqualTo(actual.getFilters()))
            .satisfies(e -> assertThat(e.getSearchDate()).as("check searchDate").isEqualTo(actual.getSearchDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserSearchHistoryUpdatableRelationshipsEquals(UserSearchHistory expected, UserSearchHistory actual) {
        // empty method
    }
}
