package bham.team.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class WishlistAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWishlistAllPropertiesEquals(Wishlist expected, Wishlist actual) {
        assertWishlistAutoGeneratedPropertiesEquals(expected, actual);
        assertWishlistAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWishlistAllUpdatablePropertiesEquals(Wishlist expected, Wishlist actual) {
        assertWishlistUpdatableFieldsEquals(expected, actual);
        assertWishlistUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWishlistAutoGeneratedPropertiesEquals(Wishlist expected, Wishlist actual) {
        assertThat(expected)
            .as("Verify Wishlist auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWishlistUpdatableFieldsEquals(Wishlist expected, Wishlist actual) {
        assertThat(expected)
            .as("Verify Wishlist relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getVisibility()).as("check visibility").isEqualTo(actual.getVisibility()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWishlistUpdatableRelationshipsEquals(Wishlist expected, Wishlist actual) {
        assertThat(expected)
            .as("Verify Wishlist relationships")
            .satisfies(e -> assertThat(e.getUserDetails()).as("check userDetails").isEqualTo(actual.getUserDetails()))
            .satisfies(e -> assertThat(e.getItems()).as("check items").isEqualTo(actual.getItems()));
    }
}
